#config datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_micropayment
    username : postgres
    password : root
    driverClassName : org.postgresql.Driver
  jpa : 
    hibernate:
      ddl-auto: update

#server config
server:
  port : 100